### ISSUE TITLE
rediseño del portal

### ISSUE THREAD

**Issue by josea6965** [josea6965/ProyectoTI#7]
todo lo relacionado de los pasos para rediseñar el portal

**Comment by josea6965** [comment]
primer promp necesito identificar los elementos de un portal de freshservice para poder hacer la modificaciones de forma controlada

1. cambiar el color que esta en medio de la pagina
2. colocar una foto de fondo

**Comment by josea6965** [comment]
¡Claro! Para identificar y modificar los elementos de un portal de Freshservice (como colores y fondo), normalmente se hace a través de la personalización del portal usando CSS y, en algunos casos, con acceso al código HTML del tema del portal. Aquí tienes una guía paso a paso para hacerlo de forma controlada:

### 1. Inspecciona los Elementos del Portal
Debes identificar los elementos exactos que quieres modificar:

- Abre el portal en tu navegador (Chrome, Firefox, etc).
- Haz clic derecho sobre la zona que quieres modificar (por ejemplo, el área central de la página) y selecciona “Inspeccionar” o “Inspeccionar elemento”.
- Esto abrirá las herramientas de desarrollador donde podrás ver el HTML y CSS relacionados.

### 2. Cambiar el Color Central de la Página

- Localiza la clase, id o elemento HTML que corresponde al área central.
- Usualmente, será algo como `.container`, `.main-content`, `#content`, etc., pero depende del tema de tu portal.
- Anota el selector CSS (por ejemplo: `.main-content`).

**Ejemplo de CSS para cambiar el color de fondo central:**
```css
.main-content {
    background-color: #f0f0f0 !important; /* Cambia el color por el que prefieras */
}
```

### 3. Colocar una Foto de Fondo

- Para poner una imagen de fondo en toda la página, identifica el selector del elemento más externo (ejemplo: `body` o `.portal-container`).
- Usa la propiedad `background-image`.

**Ejemplo de CSS para poner una foto de fondo:**
```css
body {
    background-image: url('URL-DE-TU-IMAGEN');
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
}
```
> _Reemplaza `'URL-DE-TU-IMAGEN'` por la URL directa de la imagen que quieres usar. Puede ser una imagen subida a tu servidor o a Freshservice si lo permite._

### 4. Aplica los Cambios de Forma Controlada

- En Freshservice, ve a **Admin > Portals > Personalizar Portal** (o similar).
- Busca la sección de **CSS personalizado** (Custom CSS) o **Editar tema**.
- Pega el código CSS que preparaste en los pasos anteriores.
- Guarda cambios y revisa cómo se ven en el portal (haz refresh a la página).

### 5. Buenas Prácticas

- Haz una copia de seguridad del CSS original antes de modificarlo.
- Haz los cambios primero en un entorno de prueba o usa la opción “Vista previa” si está disponible.
- Documenta los cambios realizados (qué selectores y colores usaste) para mantener un control.

---

¿Quieres que te ayude a escribir el CSS específico? Si puedes compartir una captura de pantalla o el HTML/CSS de la parte central del portal, puedo darte el selector exacto y el código listo para copiar y pegar.

**Comment by mbeatrizrg** [comment]
Hola prueba de interacción

**Comment by mbeatrizrg** [comment]
cambiar el background de tickets: 

- ahora quiero cambiar el background de los tickets este es el nombre asignado, el problema es el que el background esta dividido en dos partes: .fw-searchbar-wrapper { y este .fw-page-title-wrapper {

¡Perfecto! Si quieres cambiar el fondo de ambas partes (la barra de búsqueda y el título de página) usando una imagen o color para cada una, puedes hacerlo agregando CSS personalizado para ambas clases.

### 1. Fondo con una imagen para ambas secciones (misma imagen)
Si deseas usar la misma imagen de fondo para ambas, puedes usar este CSS:

```css
.fw-searchbar-wrapper,
.fw-page-title-wrapper {
  background: url('https://i.imgur.com/L9FLij0.jpg') no-repeat center center fixed !important;
  background-size: cover !important;
}
```

### 2. Fondo diferente para cada sección
Si prefieres usar imágenes diferentes, simplemente cambia la URL para cada clase:

```css
.fw-searchbar-wrapper {
  background: url('URL_IMAGEN_BARRA_BUSQUEDA') no-repeat center center fixed !important;
  background-size: cover !important;
}

.fw-page-title-wrapper {
  background: url('URL_IMAGEN_TITULO') no-repeat center center fixed !important;
  background-size: cover !important;
}
```
Sustituye `URL_IMAGEN_BARRA_BUSQUEDA` y `URL_IMAGEN_TITULO` por los enlaces directos de las imágenes que quieras mostrar.

### 3. Fondo sólido (color) para ambas
Si solo deseas un color de fondo (por ejemplo, blanco):

```css
.fw-searchbar-wrapper,
.fw-page-title-wrapper {
  background-color: #ffffff !important; /* Cambia el código de color a tu preferencia */
}
```

---

**Recuerda:**  
- Este CSS debes pegarlo en la sección de “CSS personalizado” de Freshdesk.
- Si el fondo sigue viéndose dividido, revisa si hay paddings o bordes que puedan estar causando la separación. Puedes ajustar o eliminar esos estilos también con CSS.

¿Quieres que te ayude a unificar visualmente ambas secciones para que parezcan una sola? ¿O necesitas que te ayude con los enlaces directos para las imágenes?
